services:
  - type: web
    name: spyder-books-connector
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_standalone:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
